title: Matthew Casali 
email: casali.ma98@gmail.com
phone: "+1 (650)-799-5462"
description: I am an acoustic engineer that focuses on hardware development, real-time DSP, and machine learning among other random projects!
theme: minima # Or any theme you've chosen
baseurl: ""
url: "https://ma-casali.github.io"

collections:
  projects:
    output: true
    permalink: /:collection/:path/

markdown: kramdown
kramdown:
  math_engine: mathjax

# Social links
github_username: ma-casali
linkedin_username: matthew-casali-761158133