title: Matthew Casali Project Portfolio
email: casali.ma98@example.com
description: >- 
  Acoustic engineer portfolio featuring mobile apps, 
  Python automation, and hardware engineering.
theme: minima # Or any theme you've chosen
baseurl: ""
url: "https://ma-casali.github.io"
